spring.application.name=school

# Enable Virtual Threads
spring.threads.virtual.enabled=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5332/school
spring.datasource.username=admin
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Expose Actuator Endpoints (Health, Info, Metrics, Prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus,beans

# Show detailed health (disk space, db connection status)
management.endpoint.health.show-details=always

# Enable Prometheus format for Micrometer
management.prometheus.metrics.export.enabled=true

# Custom path for the UI (optional, default is /swagger-ui.html)
# springdoc.swagger-ui.path=/swagger-ui
# Sort endpoints alphabetically by HTTP method
springdoc.swagger-ui.operations-sorter=alpha
# Enable the "Try it out" button by default
springdoc.swagger-ui.try-it-out-enabled=true

# springdoc.swagger-ui.use-root-path=true   
springdoc.swagger-ui.disable-swagger-default-url=true

# Force Spring to send color codes to the terminal
spring.output.ansi.enabled=always

# Optional: Make the logs even more readable by shortening the logger names
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}